files:
  include:
    - 'src/**/**.s+(a|c)ss'
  options:
    formatter: prettier
    merge-default-rules: false
rules:
  border-zero: 2
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths: 2
  empty-line-between-blocks: 2
  final-newline: 2
  leading-zero: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-extends: 1
  no-ids: 2
  no-vendor-prefixes: 0
  no-important: 1
  no-debug: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 1
  no-url-protocols:
    - 2
    - allow-protocol-relative-urls: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  one-declaration-per-line: 2
  placeholder-name-format: 1
  property-sort-order:
    - 1
    - order: 'smacss'
  quotes: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  variable-name-format: 1
  url-quotes: 2
  zero-unit: 2
